### ISSUE TITLE
release based on mutt-1.5.24

### ISSUE THREAD

**Issue by 0-wiz-0** [karelzak/mutt-kz#118]
mutt-1.5.24 was release on August 31, 2015.
Please merge the changes and make a release based on that version. Thank you!

**Comment by hurricanehrndz** [comment]
Would this entail cherry picking each commit from upstream?

**Comment by 0-wiz-0** [comment]
I would import the old version that the current mutt-kz version is based off on a branch, merge it to master (which would have just the local developments as diff) and then do the same for the 1.5.24 release, which should only give merge problems when both mutt and mutt-kz modified the same code. 

But I don't really care which way it is done :-)

**Comment by hurricanehrndz** [comment]
I was hoping karelzak would respond. I would be more then happy to try and tackle it.

**Comment by karelzak** [comment]
I'd like to do that, but I'm too busy with another stuff now. The number of the changes is relatively small, so I usually create a branch where I cherry-pick from mutt upstream. Volunteers?

I use git-remote-hg to fetch from mutt upstream, my git config:

remote.upstream.url=hg::http://dev.mutt.org/hg/mutt
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
branch.upstream.remote=upstream
branch.upstream.merge=refs/heads/master

**Comment by hurricanehrndz** [comment]
@karelzak  Thanks. I will try and give it a shot. Thanks.

**Comment by timofonic** [comment]
Any news?

**Comment by hurricanehrndz** [comment]
I personally haven't had time. It is still something I wish to tackle as a
learning experience.

**Comment by flatcap** [comment]
I sent this to the mutt-kz mailing list -- it bounced (even though it says I'm subscribed).
I send this to @karelzak but I haven't heard back (in nearly a week) -- perhaps he's on holiday.

---

In issue #118 Thomas Klausner asks if someone could update notmuch to
mutt-1.5.24.  Done.  That, and much much more...

mutt-kz consists of quite a few elements:

Major features:
-     sidebar
-     notmuch

Minor features:
-     conditional dates
-     index-color
-     nested-if
-     progress bar
-     quasi-delete
-     status-color
-     tls-sni

Misc:
- bug-fixes for Mutt

However, the current version of mutt-kz is missing:
-     Some important mutt code commits
-     Most of the translation commits
-     Many bugfixes in the minor features
-     My wonderful new version of the sidebar patch

I've brought mutt-kz up-to-date.  The branch names in [] refer to my
work repository on github.  The diagram, below, may help you understand
the relationships between the branches (red: mutt; green: sidebar;
cyan: notmuch).

    https://github.com/neomutt/flatcap
    https://flatcap.org/mutt/flatcap.png

I started with the latest version of mutt-kz [kz/master] which contains
394 commits since the Last Common Ancestor with mutt [mutt/lca].

Rebase onto:
    [mutt/1.5.24]              -> [kz/rebase1] = 160 commits
    [combine/minor/20160307]   -> [kz/rebase2] = 148 commits
    [combine/sidebar/20160307] -> [kz/rebase3] = 129 commits

Any mutt-kz bug-fixes that weren't notuch-related have been moved to
either [feature/bugfix] or the relevant feature branch.

The minor features have been merged into [combine/minor/20160307]
The icons represent the order in which the features were merged.

This brings mutt-kz now up-to-date, but still needs a little tidying.

Refactor:

[kz/refactor1] = 116 commits
-   Tidy remaining rebase artifacts
        I've tweaked the history a little here (in very minor ways).
	e.g. folded pairs like:
            Introduce typo / Fix typo
    Move notmuch build changes to beginning

[kz/refactor2] [kz/release2] = 110 + 2 commits
-   Factor out kz-build-related commit
    *   The kz-version number isn't a part of the notmuch code.
    *   gitignore changes folded
    *   kz-versioning changes folded

[kz/release2] : yellow on diagram, represents the kz-versioning.
These are changes you want for mutt-kz, but don't want to be merged
into Mutt upstream.

[kz/refactor3] [kz/release3] = 110 + 2 commits
-   Trailing whitespace
    *   Rework all the commits to prevent the introduction of trailing whitespace.
-   Tidy commit messages
    *   Most commits in the repo were prefixed with "notmuch:".  Now the
    *   notmuch code is isolated in its own branch, the prefix isn't needed.
-   Fold commit messages
    *   Fit to git standards

The code REMAINS THE SAME, but the 'churn' is reduced
This should making rebasing simpler.

I've been very careful not to make any functional changes and the
authorship of commits is maintained.

What next?

Adoption -- I would like you to adopt one of these branches.
-   Ideally [kz/refactor3]

Once you've picked a repo, I will start submitting changes to:
-   Tidy the Sidebar code that Notmuch introduces
-   Fix mutt-kz's remaining Sidebar issues
-   Rename <sidebar-toggle> to <sidebar-toggle-virtual>
        Sidebar currently has <sidebar-toggle-visible>
-   Integrate [combine/extra/20160307]
        Number of useful small features
-   Integrate other downstream/distro bugfixes

Hope this all makes sense.

-- 
Rich Russon (FlatCap) <rich@flatcap.org>

**Comment by flatcap** [comment]
- [NeoMutt project](https://github.com/neomutt/neomutt) for the stable work.
- [FlatCap's workspace](https://github.com/neomutt/flatcap) - under heavy development
- [FlatCap's repo diagram](https://flatcap.org/mutt/flatcap.png)

**Comment by hurricanehrndz** [comment]
Is combine sidebar missing in your diagram?

**Comment by flatcap** [comment]
@hurricanehrndz - Not missing, just colour-coded.
The "minor" patches are all given icons -- they are combined in the big white box with icons.
The sidebar is merged on top of the minors (green - 20160307).
Then notmuch is merged on top of sidebar (various light blue boxes).

It's a complicated diagram mainly to keep my head straight.
Hopefully, things will soon get simplified.

**Comment by hurricanehrndz** [comment]
@flatcap 
Awesome. Thank you. This is very nice work. If for whatever reason @karelzak doesn't not pick a branch are you still going to progress with the remaining fixes you mentioned:
```
However, the current version of mutt-kz is missing:

Some important mutt code commits
Most of the translation commits
Many bugfixes in the minor features
My wonderful new version of the sidebar patch
```

**Comment by hurricanehrndz** [comment]
@flatcap,

PS the diagram is also very legible and I suspected as much. It is just that no where there doesn't it state sidebar patch. I have not read into the sidebar patch, but I'm guess those patch are what constitutes the sidebar.

**Comment by flatcap** [comment]
@hurricanehrndz 
I just received an email from @karelzak and he seems keen to adopt the changes.
The "missing" changes are mostly upstream-mutt and the new sidebar.
After synchronisation, they'll all be fixed.

It's very bad form, but I released a diagram without a key.  Shame on me :-)
Mutt is red, Notmuch is light blue, Sidebar is green (20160307 is the latest version).
The yellow "leaves" are the mutt-kz build changes and version numbers.

**Comment by karelzak** [comment]
On Thu, Jan 07, 2016 at 07:18:16AM -0800, Thomas Klausner wrote:
> Please merge the changes and make a release based on that version Thank you!

I'll very probably merge stuff from neomutt/mutt-kz (from Richard
Russon). The result should be mutt-kz synced with the current mutt
upstream. 

It seems that after years mutt upstream is again active, so it's
probably good idea to regularly rebase our changes to keep things up
to date. (It means that "git pull --force" or so will be necessary to
fetch mutt-kz.)

The next step (I hope end of this week or begin of the next week) will
be release mutt-kz tarball.

And sorry for my delays, I'm busy with util-linux and with work on
RHEL...

    Karel

-- 
 Karel Zak  <kzak@redhat.com>
 http://karelzak.blogspot.com

**Comment by karelzak** [comment]
On Mon, Mar 21, 2016 at 12:00:04PM +0100, Karel Zak wrote:
> On Thu, Jan 07, 2016 at 07:18:16AM -0800, Thomas Klausner wrote:
> > Please merge the changes and make a release based on that version Thank you!
> 
> I'll very probably merge stuff from neomutt/mutt-kz (from Richard
> Russon). The result should be mutt-kz synced with the current mutt
> upstream. 

Neomutt tracks lots of branches, are you going to merge just the ones
related to mutt upstream?

**Comment by flatcap** [comment]
The ['new' mutt-kz](https://github.com/neomutt/mutt-kz) **only** contains the features that the ['old' mutt-kz](https://github.com/karelzak/mutt-kz) had:

- bug-fixes
- quasi-delete
- progress
- status-color
- index-color
- nested-if
- cond-date
- tls-sni
- sidebar

Because the new repo is derived from [NeoMutt](https://github.com/neomutt/neomutt), it's simple to merge the extra features, if they're wanted:

- fmemopen
- ifdef
- initials
- trash

The plan is to get **all** the features including Sidebar and NotMuch merged into Mutt.

**Comment by karelzak** [comment]
On Mon, Mar 21, 2016 at 02:35:07PM +0100, David Sterba wrote:
> On Mon, Mar 21, 2016 at 12:00:04PM +0100, Karel Zak wrote:
> > On Thu, Jan 07, 2016 at 07:18:16AM -0800, Thomas Klausner wrote:
> > > Please merge the changes and make a release based on that version Thank you!
> > 
> > I'll very probably merge stuff from neomutt/mutt-kz (from Richard
> > Russon). The result should be mutt-kz synced with the current mutt
> > upstream. 
> 
> Neomutt tracks lots of branches, are you going to merge just the ones
> related to mutt upstream?

Well, Richard has prepared a branch for me with notmuch stuff as well
as another features already integrated to mutt-kz. It also contains a
new sidebar (seems more readable). 

Try:

  git remote add -f neomutt-kz https://github.com/neomutt/mutt-kz
  git checkout -b neomutt-kz neomutt-kz/mutt-kz

  ./prepare
  ./configure --enable-hcache --enable-flock --enable-notmuch --enable-sidebar --disable-fcntl
  make

  ./mutt

... this is what I currently using on my workstation to test it.

I found a small difference in sidebar .muttrc stuff (some options have
been renamed, but nothing critical).

See below git diff stuff (exclude po/ docs/ README*, ).

    Karel


 .hgignore               |    5 +
 .hgsigs                 |    1 +
 .hgtags                 |    2 +
 Makefile.am             |   21 +-
 OPS                     |    9 -
 OPS.SIDEBAR             |    9 +
 PATCHES                 |   10 +-
 UPDATING                |   33 +
 UPDATING.kz             |    6 +-
 VERSION                 |    2 +-
 browser.c               |   12 +-
 buffy.c                 |  360 ++++---
 buffy.h                 |   13 +-
 build-release           |    6 +-
 color.c                 |  198 ++--
 commands.c              |    4 +-
 compose.c               |    8 +-
 configure.ac            |   19 +-
 copy.c                  |    3 +-
 crypt-gpgme.c           |   91 +-
 crypt.c                 |   64 +-
 curs_lib.c              |  101 +-
 curs_main.c             |  293 +++---
 flags.c                 |    8 +-
 flymake.am              |   12 +
 functions.h             |   43 +-
 globals.h               |   17 +-
 handler.c               |  230 +++--
 hcache.c                |   20 +-
 hdrline.c               |  339 +++----
 help.c                  |    2 +-
 hook.c                  |   17 +
 imap/Makefile.am        |    1 +
 imap/auth_gss.c         |    6 +-
 imap/command.c          |   13 +-
 imap/imap.c             |   14 +
 imap/message.c          |    2 +-
 imap/util.c             |    2 +-
 init.h                  |  240 +++--
 keymap.c                |    1 +
 mailbox.h               |    2 +
 main.c                  |   28 +
 mbox.c                  |    4 +
 menu.c                  |  109 +-
 mh.c                    |   63 +-
 mkchangelog.sh          |    2 +-
 mutt.h                  |   13 +-
 mutt_crypt.h            |    4 +
 mutt_curses.h           |   21 +-
 mutt_menu.h             |    3 +
 mutt_ssl.c              |    2 +-
 muttlib.c               |  142 +--
 mx.c                    |   32 +-
 mx.h                    |    5 +-
 pager.c                 |   70 +-
 pgp.c                   |   98 +-
 pop_lib.c               |    1 +
 protos.h                |   10 +-
 recvattach.c            |    3 +-
 sendlib.c               |    3 +-
 sidebar.c               | 1421 ++++++++++++++++++--------
 sidebar.h               |   29 +-
 smime.c                 |    2 +-
 sort.h                  |    5 +-
 txt2c.sh                |    6 +-
 118 files changed, 28628 insertions(+), 18737 deletions(-)

-- 
 Karel Zak  <kzak@redhat.com>
 http://karelzak.blogspot.com

**Comment by karelzak** [comment]
On Mon, Mar 21, 2016 at 05:28:39PM +0100, Karel Zak wrote:
> On Mon, Mar 21, 2016 at 02:35:07PM +0100, David Sterba wrote:
> > On Mon, Mar 21, 2016 at 12:00:04PM +0100, Karel Zak wrote:
> > > On Thu, Jan 07, 2016 at 07:18:16AM -0800, Thomas Klausner wrote:
> > > > Please merge the changes and make a release based on that version Thank you!
> > > 
> > > I'll very probably merge stuff from neomutt/mutt-kz (from Richard
> > > Russon). The result should be mutt-kz synced with the current mutt
> > > upstream. 
> > 
> > Neomutt tracks lots of branches, are you going to merge just the ones
> > related to mutt upstream?
> 
> Well, Richard has prepared a branch for me with notmuch stuff as well
> as another features already integrated to mutt-kz. It also contains a
> new sidebar (seems more readable). 
> 
> Try:
> 
>   git remote add -f neomutt-kz https://github.com/neomutt/mutt-kz
>   git checkout -b neomutt-kz neomutt-kz/mutt-kz

 Note that I've created neo-mutt-kz branch at your mutt-kz repository 
 with bugfixes for Richard. So you can use it

  git pull
  git checkout neo-mutt-kz

    Karel

-- 
 Karel Zak  <kzak@redhat.com>
 http://karelzak.blogspot.com

**Comment by karelzak** [comment]
On 03/21/16 at 12:00pm, Karel Zak wrote:
> On Thu, Jan 07, 2016 at 07:18:16AM -0800, Thomas Klausner wrote:
> > Please merge the changes and make a release based on that version Thank you!
> 
> I'll very probably merge stuff from neomutt/mutt-kz (from Richard
> Russon). The result should be mutt-kz synced with the current mutt
> upstream. 
> 
> It seems that after years mutt upstream is again active, so it's
> probably good idea to regularly rebase our changes to keep things up
> to date. (It means that "git pull --force" or so will be necessary to
> fetch mutt-kz.)

But that would break the release process. How you could tag a release if we
will always rebase the projects patches?


vmjl

**Comment by flatcap** [comment]
> But that would break the release process. How you could tag a release if we will always rebase the projects patches?

**Yes**.  Releases would not look nice.  They wouldn't look connected to each another.

**No**.  Releases would still work.  Any tags or branches in git will preserve the **complete** history to that point.

It's a trade-off.  Rebasing isn't **necessary**, but it makes our work easier to maintain.

We don't have to care for old releases of our features.  The latest release should be all the user needs.

**Comment by karelzak** [comment]
On Tue, Mar 22, 2016 at 10:22:24AM +0100, Víctor M. Jáquez L. wrote:
> On 03/21/16 at 12:00pm, Karel Zak wrote:
> > On Thu, Jan 07, 2016 at 07:18:16AM -0800, Thomas Klausner wrote:
> > > Please merge the changes and make a release based on that version Thank you!
> > 
> > I'll very probably merge stuff from neomutt/mutt-kz (from Richard
> > Russon). The result should be mutt-kz synced with the current mutt
> > upstream. 
> > 
> > It seems that after years mutt upstream is again active, so it's
> > probably good idea to regularly rebase our changes to keep things up
> > to date. (It means that "git pull --force" or so will be necessary to
> > fetch mutt-kz.)
> 
> But that would break the release process. How you could tag a release if we
> will always rebase the projects patches?

 Good point, then we can create a separate branch for each release and
 maintain (and tag) the release in the branch without rebases. The
 rebase should be possible in the master (=development) branch only.


    Karel

-- 
 Karel Zak  <kzak@redhat.com>
 http://karelzak.blogspot.com

**Comment by anarcat** [comment]
1.6 is out now, you may want to reconsider this work.

**Comment by flatcap** [comment]
@anarcat  
I've *just* released NeoMutt rebased to mutt-1.6.0.
Because very little happened in the last six months it wasn't a big job.
https://github.com/neomutt/neomutt/releases/latest

@karelzak 
I've pushed a stripped down version to github:
https://github.com/neomutt/mutt-kz6

There are no code changes, just the rebase to mutt-1.6.0.
A few of the commits that _were_ in [features/bug-fixes] are now in mutt proper.

**Comment by karelzak** [comment]
Cool, thanks... going to use it.

**Comment by karelzak** [comment]
@flatcap I don't see upstream tags in your branches (at least in mutt-kz6 repo). It would be nice to have it there. Maybe you just forgot "git push --tags" or so.

**Comment by flatcap** [comment]
@karelzak 
Yeah, they'd be kinda useful :-)

feature/* (15)
    feature branches

Mutt official releases
(I didn't have a need for any older tags)
    mutt/1.5.24
    mutt/1.6.0

Mutt development
    mutt/default

NeoMutt development
    neomutt

NeoMutt releases (5)
    neomutt-YYYYMMDD

Sidebar
    sidebar/20160307

There are a duplicate set of tags ending in 5 which are for the Mutt-1.5.24
series.

**Comment by karelzak** [comment]
BTW, because we use rebase now, then fetch tags from mutt upstream (I use hg driver for git) seems work as expected and I have upstream tags (e.g. mutt-1-6-rel)  in the  karelzak/mutt-kz now.

**Comment by hurricanehrndz** [comment]
Just want to say thanks guys for your hard work. I'm running 1.6.0.1 now and it seems to be working pretty good.
